include: package:flutter_lints/flutter.yaml

analyzer:
  exclude: 
    - "**.g.dart"
    - "**.freezed.dart"
    - "app_localizations**.dart"
    - build/**
    - android/**
    - ios/**
    - web/**
    - windows/**
    - macos/**
    - linux/**

linter:
  rules:
    - prefer_const_constructors
    - prefer_const_declarations
    - prefer_const_literals_to_create_immutables

plugins:
  riverpod_lint: 3.1.8
