name: animebox
description: "A new Flutter project."
publish_to: 'none' 

version: 0.1.0+1

assets:
  - logo.png

environment:
  sdk: ^3.11.4

dependencies:
  flutter:
    sdk: flutter

  rust_lib_animebox:
    path: rust_builder
  flutter_rust_bridge: 2.13.0-beta.5
  flutter_inappwebview: ^6.1.5
  dynamic_color: ^1.6.7
  logger: ^2.7.0
  path_provider: ^2.1.5
  path: ^1.9.1
  settings_ui: ^3.0.1

  flutter_localizations:
    sdk: flutter
  file_picker: ^11.0.2
  media_kit: ^1.2.6
  media_kit_video: ^2.0.1
  media_kit_libs_video: ^1.0.7 
  gradient_blur: ^1.0.2+1
  transparent_image: ^2.0.1
  freezed_annotation: ^3.1.0


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0
  integration_test:
    sdk: flutter
  freezed: ^3.2.5
  build_runner: ^2.15.0

flutter:
  uses-material-design: true
  generate: true

