// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: unused_import, unused_element, unnecessary_import, duplicate_ignore, invalid_use_of_internal_member, annotate_overrides, non_constant_identifier_names, curly_braces_in_flow_control_structures, prefer_const_literals_to_create_immutables, unused_field

// Static analysis wrongly picks the IO variant, thus ignore this
// ignore_for_file: argument_type_not_assignable

import 'api/app/configuration/models.dart';
import 'api/app/languages.dart';
import 'api/app/logging.dart';
import 'api/app/sections.dart';
import 'api/app/themes.dart';
import 'api/data/caching/anime_sources.dart';
import 'api/data/caching/utils.dart';
import 'api/data/metadata/myanimelist.dart';
import 'api/data/metadata/utils.dart';
import 'api/data/models.dart';
import 'api/data/video_providers/mp4upload.dart';
import 'api/data/video_providers/streamtape.dart';
import 'api/data/video_providers/streamwish.dart';
import 'api/data/video_providers/utils.dart';
import 'api/data/video_providers/yourupload.dart';
import 'api/server/handler.dart';
import 'api/server/models.dart';
import 'dart:async';
import 'dart:convert';
import 'frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated_web.dart';

abstract class RustLibApiImplPlatform extends BaseApiImpl<RustLibWire> {
  RustLibApiImplPlatform({
    required super.handler,
    required super.wire,
    required super.generalizedFrbRustBinding,
    required super.portManager,
  });

  CrossPlatformFinalizerArg
  get rust_arc_decrement_strong_count_AnimeSourcesCacheManagerPtr => wire
      .rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerAnimeSourcesCacheManager;

  @protected
  AnyhowException dco_decode_AnyhowException(dynamic raw);

  @protected
  AnimeSourcesCacheManager
  dco_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerAnimeSourcesCacheManager(
    dynamic raw,
  );

  @protected
  AnimeSourcesCacheManager
  dco_decode_Auto_RefMut_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerAnimeSourcesCacheManager(
    dynamic raw,
  );

  @protected
  AnimeSourcesCacheManager
  dco_decode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerAnimeSourcesCacheManager(
    dynamic raw,
  );

  @protected
  Map<String, String> dco_decode_Map_String_String_None(dynamic raw);

  @protected
  Map<String, CacheRefreshError> dco_decode_Map_String_cache_refresh_error_None(
    dynamic raw,
  );

  @protected
  Map<String, List<AnimeSource>> dco_decode_Map_String_list_anime_source_None(
    dynamic raw,
  );

  @protected
  AnimeSourcesCacheManager
  dco_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerAnimeSourcesCacheManager(
    dynamic raw,
  );

  @protected
  RustStreamSink<RefreshJob> dco_decode_StreamSink_refresh_job_Sse(dynamic raw);

  @protected
  String dco_decode_String(dynamic raw);

  @protected
  AnimeSources dco_decode_TraitDef_AnimeSources(dynamic raw);

  @protected
  CacheSource dco_decode_TraitDef_CacheSource(dynamic raw);

  @protected
  Expirable dco_decode_TraitDef_Expirable(dynamic raw);

  @protected
  GetPath dco_decode_TraitDef_GetPath(dynamic raw);

  @protected
  ReadWrite dco_decode_TraitDef_ReadWrite(dynamic raw);

  @protected
  SlimMetaGetter dco_decode_TraitDef_SlimMetaGetter(dynamic raw);

  @protected
  ToDateObject dco_decode_TraitDef_ToDateObject(dynamic raw);

  @protected
  ToSerieMetadata dco_decode_TraitDef_ToSerieMetadata(dynamic raw);

  @protected
  ToSlimMeta dco_decode_TraitDef_ToSlimMeta(dynamic raw);

  @protected
  AdvancedConfig dco_decode_advanced_config(dynamic raw);

  @protected
  AnimeBoxConfig dco_decode_anime_box_config(dynamic raw);

  @protected
  AnimeSource dco_decode_anime_source(dynamic raw);

  @protected
  AppLanguages dco_decode_app_languages(dynamic raw);

  @protected
  AppearanceConfig dco_decode_appearance_config(dynamic raw);

  @protected
  bool dco_decode_bool(dynamic raw);

  @protected
  AnimeBoxConfig dco_decode_box_autoadd_anime_box_config(dynamic raw);

  @protected
  CoreLoggerSettings dco_decode_box_autoadd_core_logger_settings(dynamic raw);

  @protected
  DateObject dco_decode_box_autoadd_date_object(dynamic raw);

  @protected
  int dco_decode_box_autoadd_i_32(dynamic raw);

  @protected
  MetadataSources dco_decode_box_autoadd_metadata_sources(dynamic raw);

  @protected
  MP4Upload dco_decode_box_autoadd_mp_4_upload(dynamic raw);

  @protected
  SerieMetadata dco_decode_box_autoadd_serie_metadata(dynamic raw);

  @protected
  StreamTape dco_decode_box_autoadd_stream_tape(dynamic raw);

  @protected
  StreamWish dco_decode_box_autoadd_stream_wish(dynamic raw);

  @protected
  int dco_decode_box_autoadd_u_32(dynamic raw);

  @protected
  YourUpload dco_decode_box_autoadd_your_upload(dynamic raw);

  @protected
  CacheRefreshError dco_decode_cache_refresh_error(dynamic raw);

  @protected
  ConfigServer dco_decode_config_server(dynamic raw);

  @protected
  CoreLoggerSettings dco_decode_core_logger_settings(dynamic raw);

  @protected
  DateObject dco_decode_date_object(dynamic raw);

  @protected
  DownloadsConfig dco_decode_downloads_config(dynamic raw);

  @protected
  double dco_decode_f_64(dynamic raw);

  @protected
  HomeTabs dco_decode_home_tabs(dynamic raw);

  @protected
  int dco_decode_i_32(dynamic raw);

  @protected
  PlatformInt64 dco_decode_i_64(dynamic raw);

  @protected
  Language dco_decode_language(dynamic raw);

  @protected
  LibraryConfig dco_decode_library_config(dynamic raw);

  @protected
  List<String> dco_decode_list_String(dynamic raw);

  @protected
  List<AnimeSource> dco_decode_list_anime_source(dynamic raw);

  @protected
  List<ConfigServer> dco_decode_list_config_server(dynamic raw);

  @protected
  List<MetadataSourceConfig> dco_decode_list_metadata_source_config(
    dynamic raw,
  );

  @protected
  Uint8List dco_decode_list_prim_u_8_strict(dynamic raw);

  @protected
  List<(String, CacheRefreshError)>
  dco_decode_list_record_string_cache_refresh_error(dynamic raw);

  @protected
  List<(String, List<AnimeSource>)>
  dco_decode_list_record_string_list_anime_source(dynamic raw);

  @protected
  List<(String, String)> dco_decode_list_record_string_string(dynamic raw);

  @protected
  List<SearchResult> dco_decode_list_search_result(dynamic raw);

  @protected
  List<SlimSerieMetadata> dco_decode_list_slim_serie_metadata(dynamic raw);

  @protected
  LocalStorageConfig dco_decode_local_storage_config(dynamic raw);

  @protected
  LogLevel dco_decode_log_level(dynamic raw);

  @protected
  MetadataConfig dco_decode_metadata_config(dynamic raw);

  @protected
  MetadataSourceConfig dco_decode_metadata_source_config(dynamic raw);

  @protected
  MetadataSources dco_decode_metadata_sources(dynamic raw);

  @protected
  MP4Upload dco_decode_mp_4_upload(dynamic raw);

  @protected
  String? dco_decode_opt_String(dynamic raw);

  @protected
  DateObject? dco_decode_opt_box_autoadd_date_object(dynamic raw);

  @protected
  int? dco_decode_opt_box_autoadd_i_32(dynamic raw);

  @protected
  MetadataSources? dco_decode_opt_box_autoadd_metadata_sources(dynamic raw);

  @protected
  SerieMetadata? dco_decode_opt_box_autoadd_serie_metadata(dynamic raw);

  @protected
  int? dco_decode_opt_box_autoadd_u_32(dynamic raw);

  @protected
  List<String>? dco_decode_opt_list_String(dynamic raw);

  @protected
  PlaybackConfig dco_decode_playback_config(dynamic raw);

  @protected
  (String, CacheRefreshError) dco_decode_record_string_cache_refresh_error(
    dynamic raw,
  );

  @protected
  (String, List<AnimeSource>) dco_decode_record_string_list_anime_source(
    dynamic raw,
  );

  @protected
  (String, String) dco_decode_record_string_string(dynamic raw);

  @protected
  RefreshJob dco_decode_refresh_job(dynamic raw);

  @protected
  SearchResult dco_decode_search_result(dynamic raw);

  @protected
  SerieMetaConfidence dco_decode_serie_meta_confidence(dynamic raw);

  @protected
  SerieMetadata dco_decode_serie_metadata(dynamic raw);

  @protected
  SerieStatus dco_decode_serie_status(dynamic raw);

  @protected
  ServersConfig dco_decode_servers_config(dynamic raw);

  @protected
  SlimSerieMetadata dco_decode_slim_serie_metadata(dynamic raw);

  @protected
  StreamTape dco_decode_stream_tape(dynamic raw);

  @protected
  StreamWish dco_decode_stream_wish(dynamic raw);

  @protected
  ThemeModes dco_decode_theme_modes(dynamic raw);

  @protected
  Themes dco_decode_themes(dynamic raw);

  @protected
  int dco_decode_u_32(dynamic raw);

  @protected
  int dco_decode_u_8(dynamic raw);

  @protected
  void dco_decode_unit(dynamic raw);

  @protected
  UpdateParams dco_decode_update_params(dynamic raw);

  @protected
  BigInt dco_decode_usize(dynamic raw);

  @protected
  Video dco_decode_video(dynamic raw);

  @protected
  YourUpload dco_decode_your_upload(dynamic raw);

  @protected
  AnyhowException sse_decode_AnyhowException(SseDeserializer deserializer);

  @protected
  AnimeSourcesCacheManager
  sse_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerAnimeSourcesCacheManager(
    SseDeserializer deserializer,
  );

  @protected
  AnimeSourcesCacheManager
  sse_decode_Auto_RefMut_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerAnimeSourcesCacheManager(
    SseDeserializer deserializer,
  );

  @protected
  AnimeSourcesCacheManager
  sse_decode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerAnimeSourcesCacheManager(
    SseDeserializer deserializer,
  );

  @protected
  Map<String, String> sse_decode_Map_String_String_None(
    SseDeserializer deserializer,
  );

  @protected
  Map<String, CacheRefreshError> sse_decode_Map_String_cache_refresh_error_None(
    SseDeserializer deserializer,
  );

  @protected
  Map<String, List<AnimeSource>> sse_decode_Map_String_list_anime_source_None(
    SseDeserializer deserializer,
  );

  @protected
  AnimeSourcesCacheManager
  sse_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerAnimeSourcesCacheManager(
    SseDeserializer deserializer,
  );

  @protected
  RustStreamSink<RefreshJob> sse_decode_StreamSink_refresh_job_Sse(
    SseDeserializer deserializer,
  );

  @protected
  String sse_decode_String(SseDeserializer deserializer);

  @protected
  AdvancedConfig sse_decode_advanced_config(SseDeserializer deserializer);

  @protected
  AnimeBoxConfig sse_decode_anime_box_config(SseDeserializer deserializer);

  @protected
  AnimeSource sse_decode_anime_source(SseDeserializer deserializer);

  @protected
  AppLanguages sse_decode_app_languages(SseDeserializer deserializer);

  @protected
  AppearanceConfig sse_decode_appearance_config(SseDeserializer deserializer);

  @protected
  bool sse_decode_bool(SseDeserializer deserializer);

  @protected
  AnimeBoxConfig sse_decode_box_autoadd_anime_box_config(
    SseDeserializer deserializer,
  );

  @protected
  CoreLoggerSettings sse_decode_box_autoadd_core_logger_settings(
    SseDeserializer deserializer,
  );

  @protected
  DateObject sse_decode_box_autoadd_date_object(SseDeserializer deserializer);

  @protected
  int sse_decode_box_autoadd_i_32(SseDeserializer deserializer);

  @protected
  MetadataSources sse_decode_box_autoadd_metadata_sources(
    SseDeserializer deserializer,
  );

  @protected
  MP4Upload sse_decode_box_autoadd_mp_4_upload(SseDeserializer deserializer);

  @protected
  SerieMetadata sse_decode_box_autoadd_serie_metadata(
    SseDeserializer deserializer,
  );

  @protected
  StreamTape sse_decode_box_autoadd_stream_tape(SseDeserializer deserializer);

  @protected
  StreamWish sse_decode_box_autoadd_stream_wish(SseDeserializer deserializer);

  @protected
  int sse_decode_box_autoadd_u_32(SseDeserializer deserializer);

  @protected
  YourUpload sse_decode_box_autoadd_your_upload(SseDeserializer deserializer);

  @protected
  CacheRefreshError sse_decode_cache_refresh_error(
    SseDeserializer deserializer,
  );

  @protected
  ConfigServer sse_decode_config_server(SseDeserializer deserializer);

  @protected
  CoreLoggerSettings sse_decode_core_logger_settings(
    SseDeserializer deserializer,
  );

  @protected
  DateObject sse_decode_date_object(SseDeserializer deserializer);

  @protected
  DownloadsConfig sse_decode_downloads_config(SseDeserializer deserializer);

  @protected
  double sse_decode_f_64(SseDeserializer deserializer);

  @protected
  HomeTabs sse_decode_home_tabs(SseDeserializer deserializer);

  @protected
  int sse_decode_i_32(SseDeserializer deserializer);

  @protected
  PlatformInt64 sse_decode_i_64(SseDeserializer deserializer);

  @protected
  Language sse_decode_language(SseDeserializer deserializer);

  @protected
  LibraryConfig sse_decode_library_config(SseDeserializer deserializer);

  @protected
  List<String> sse_decode_list_String(SseDeserializer deserializer);

  @protected
  List<AnimeSource> sse_decode_list_anime_source(SseDeserializer deserializer);

  @protected
  List<ConfigServer> sse_decode_list_config_server(
    SseDeserializer deserializer,
  );

  @protected
  List<MetadataSourceConfig> sse_decode_list_metadata_source_config(
    SseDeserializer deserializer,
  );

  @protected
  Uint8List sse_decode_list_prim_u_8_strict(SseDeserializer deserializer);

  @protected
  List<(String, CacheRefreshError)>
  sse_decode_list_record_string_cache_refresh_error(
    SseDeserializer deserializer,
  );

  @protected
  List<(String, List<AnimeSource>)>
  sse_decode_list_record_string_list_anime_source(SseDeserializer deserializer);

  @protected
  List<(String, String)> sse_decode_list_record_string_string(
    SseDeserializer deserializer,
  );

  @protected
  List<SearchResult> sse_decode_list_search_result(
    SseDeserializer deserializer,
  );

  @protected
  List<SlimSerieMetadata> sse_decode_list_slim_serie_metadata(
    SseDeserializer deserializer,
  );

  @protected
  LocalStorageConfig sse_decode_local_storage_config(
    SseDeserializer deserializer,
  );

  @protected
  LogLevel sse_decode_log_level(SseDeserializer deserializer);

  @protected
  MetadataConfig sse_decode_metadata_config(SseDeserializer deserializer);

  @protected
  MetadataSourceConfig sse_decode_metadata_source_config(
    SseDeserializer deserializer,
  );

  @protected
  MetadataSources sse_decode_metadata_sources(SseDeserializer deserializer);

  @protected
  MP4Upload sse_decode_mp_4_upload(SseDeserializer deserializer);

  @protected
  String? sse_decode_opt_String(SseDeserializer deserializer);

  @protected
  DateObject? sse_decode_opt_box_autoadd_date_object(
    SseDeserializer deserializer,
  );

  @protected
  int? sse_decode_opt_box_autoadd_i_32(SseDeserializer deserializer);

  @protected
  MetadataSources? sse_decode_opt_box_autoadd_metadata_sources(
    SseDeserializer deserializer,
  );

  @protected
  SerieMetadata? sse_decode_opt_box_autoadd_serie_metadata(
    SseDeserializer deserializer,
  );

  @protected
  int? sse_decode_opt_box_autoadd_u_32(SseDeserializer deserializer);

  @protected
  List<String>? sse_decode_opt_list_String(SseDeserializer deserializer);

  @protected
  PlaybackConfig sse_decode_playback_config(SseDeserializer deserializer);

  @protected
  (String, CacheRefreshError) sse_decode_record_string_cache_refresh_error(
    SseDeserializer deserializer,
  );

  @protected
  (String, List<AnimeSource>) sse_decode_record_string_list_anime_source(
    SseDeserializer deserializer,
  );

  @protected
  (String, String) sse_decode_record_string_string(
    SseDeserializer deserializer,
  );

  @protected
  RefreshJob sse_decode_refresh_job(SseDeserializer deserializer);

  @protected
  SearchResult sse_decode_search_result(SseDeserializer deserializer);

  @protected
  SerieMetaConfidence sse_decode_serie_meta_confidence(
    SseDeserializer deserializer,
  );

  @protected
  SerieMetadata sse_decode_serie_metadata(SseDeserializer deserializer);

  @protected
  SerieStatus sse_decode_serie_status(SseDeserializer deserializer);

  @protected
  ServersConfig sse_decode_servers_config(SseDeserializer deserializer);

  @protected
  SlimSerieMetadata sse_decode_slim_serie_metadata(
    SseDeserializer deserializer,
  );

  @protected
  StreamTape sse_decode_stream_tape(SseDeserializer deserializer);

  @protected
  StreamWish sse_decode_stream_wish(SseDeserializer deserializer);

  @protected
  ThemeModes sse_decode_theme_modes(SseDeserializer deserializer);

  @protected
  Themes sse_decode_themes(SseDeserializer deserializer);

  @protected
  int sse_decode_u_32(SseDeserializer deserializer);

  @protected
  int sse_decode_u_8(SseDeserializer deserializer);

  @protected
  void sse_decode_unit(SseDeserializer deserializer);

  @protected
  UpdateParams sse_decode_update_params(SseDeserializer deserializer);

  @protected
  BigInt sse_decode_usize(SseDeserializer deserializer);

  @protected
  Video sse_decode_video(SseDeserializer deserializer);

  @protected
  YourUpload sse_decode_your_upload(SseDeserializer deserializer);

  @protected
  void sse_encode_AnyhowException(
    AnyhowException self,
    SseSerializer serializer,
  );

  @protected
  void
  sse_encode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerAnimeSourcesCacheManager(
    AnimeSourcesCacheManager self,
    SseSerializer serializer,
  );

  @protected
  void
  sse_encode_Auto_RefMut_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerAnimeSourcesCacheManager(
    AnimeSourcesCacheManager self,
    SseSerializer serializer,
  );

  @protected
  void
  sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerAnimeSourcesCacheManager(
    AnimeSourcesCacheManager self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_Map_String_String_None(
    Map<String, String> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_Map_String_cache_refresh_error_None(
    Map<String, CacheRefreshError> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_Map_String_list_anime_source_None(
    Map<String, List<AnimeSource>> self,
    SseSerializer serializer,
  );

  @protected
  void
  sse_encode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerAnimeSourcesCacheManager(
    AnimeSourcesCacheManager self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_StreamSink_refresh_job_Sse(
    RustStreamSink<RefreshJob> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_String(String self, SseSerializer serializer);

  @protected
  void sse_encode_advanced_config(
    AdvancedConfig self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_anime_box_config(
    AnimeBoxConfig self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_anime_source(AnimeSource self, SseSerializer serializer);

  @protected
  void sse_encode_app_languages(AppLanguages self, SseSerializer serializer);

  @protected
  void sse_encode_appearance_config(
    AppearanceConfig self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_bool(bool self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_anime_box_config(
    AnimeBoxConfig self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_core_logger_settings(
    CoreLoggerSettings self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_date_object(
    DateObject self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_i_32(int self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_metadata_sources(
    MetadataSources self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_mp_4_upload(
    MP4Upload self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_serie_metadata(
    SerieMetadata self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_stream_tape(
    StreamTape self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_stream_wish(
    StreamWish self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_u_32(int self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_your_upload(
    YourUpload self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_cache_refresh_error(
    CacheRefreshError self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_config_server(ConfigServer self, SseSerializer serializer);

  @protected
  void sse_encode_core_logger_settings(
    CoreLoggerSettings self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_date_object(DateObject self, SseSerializer serializer);

  @protected
  void sse_encode_downloads_config(
    DownloadsConfig self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_f_64(double self, SseSerializer serializer);

  @protected
  void sse_encode_home_tabs(HomeTabs self, SseSerializer serializer);

  @protected
  void sse_encode_i_32(int self, SseSerializer serializer);

  @protected
  void sse_encode_i_64(PlatformInt64 self, SseSerializer serializer);

  @protected
  void sse_encode_language(Language self, SseSerializer serializer);

  @protected
  void sse_encode_library_config(LibraryConfig self, SseSerializer serializer);

  @protected
  void sse_encode_list_String(List<String> self, SseSerializer serializer);

  @protected
  void sse_encode_list_anime_source(
    List<AnimeSource> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_config_server(
    List<ConfigServer> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_metadata_source_config(
    List<MetadataSourceConfig> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_prim_u_8_strict(
    Uint8List self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_record_string_cache_refresh_error(
    List<(String, CacheRefreshError)> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_record_string_list_anime_source(
    List<(String, List<AnimeSource>)> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_record_string_string(
    List<(String, String)> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_search_result(
    List<SearchResult> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_slim_serie_metadata(
    List<SlimSerieMetadata> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_local_storage_config(
    LocalStorageConfig self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_log_level(LogLevel self, SseSerializer serializer);

  @protected
  void sse_encode_metadata_config(
    MetadataConfig self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_metadata_source_config(
    MetadataSourceConfig self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_metadata_sources(
    MetadataSources self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_mp_4_upload(MP4Upload self, SseSerializer serializer);

  @protected
  void sse_encode_opt_String(String? self, SseSerializer serializer);

  @protected
  void sse_encode_opt_box_autoadd_date_object(
    DateObject? self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_opt_box_autoadd_i_32(int? self, SseSerializer serializer);

  @protected
  void sse_encode_opt_box_autoadd_metadata_sources(
    MetadataSources? self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_opt_box_autoadd_serie_metadata(
    SerieMetadata? self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_opt_box_autoadd_u_32(int? self, SseSerializer serializer);

  @protected
  void sse_encode_opt_list_String(List<String>? self, SseSerializer serializer);

  @protected
  void sse_encode_playback_config(
    PlaybackConfig self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_record_string_cache_refresh_error(
    (String, CacheRefreshError) self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_record_string_list_anime_source(
    (String, List<AnimeSource>) self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_record_string_string(
    (String, String) self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_refresh_job(RefreshJob self, SseSerializer serializer);

  @protected
  void sse_encode_search_result(SearchResult self, SseSerializer serializer);

  @protected
  void sse_encode_serie_meta_confidence(
    SerieMetaConfidence self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_serie_metadata(SerieMetadata self, SseSerializer serializer);

  @protected
  void sse_encode_serie_status(SerieStatus self, SseSerializer serializer);

  @protected
  void sse_encode_servers_config(ServersConfig self, SseSerializer serializer);

  @protected
  void sse_encode_slim_serie_metadata(
    SlimSerieMetadata self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_stream_tape(StreamTape self, SseSerializer serializer);

  @protected
  void sse_encode_stream_wish(StreamWish self, SseSerializer serializer);

  @protected
  void sse_encode_theme_modes(ThemeModes self, SseSerializer serializer);

  @protected
  void sse_encode_themes(Themes self, SseSerializer serializer);

  @protected
  void sse_encode_u_32(int self, SseSerializer serializer);

  @protected
  void sse_encode_u_8(int self, SseSerializer serializer);

  @protected
  void sse_encode_unit(void self, SseSerializer serializer);

  @protected
  void sse_encode_update_params(UpdateParams self, SseSerializer serializer);

  @protected
  void sse_encode_usize(BigInt self, SseSerializer serializer);

  @protected
  void sse_encode_video(Video self, SseSerializer serializer);

  @protected
  void sse_encode_your_upload(YourUpload self, SseSerializer serializer);
}

// Section: wire_class

class RustLibWire implements BaseWire {
  RustLibWire.fromExternalLibrary(ExternalLibrary lib);

  void
  rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerAnimeSourcesCacheManager(
    int ptr,
  ) => wasmModule
      .rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerAnimeSourcesCacheManager(
        ptr,
      );

  void
  rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerAnimeSourcesCacheManager(
    int ptr,
  ) => wasmModule
      .rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerAnimeSourcesCacheManager(
        ptr,
      );
}

@JS('wasm_bindgen')
external RustLibWasmModule get wasmModule;

@JS()
@anonymous
extension type RustLibWasmModule._(JSObject _) implements JSObject {
  external void
  rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerAnimeSourcesCacheManager(
    int ptr,
  );

  external void
  rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerAnimeSourcesCacheManager(
    int ptr,
  );
}
