// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../../../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';
import 'package:freezed_annotation/freezed_annotation.dart' hide protected;
part 'error.freezed.dart';

// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `fmt`, `fmt`, `from`, `from`, `from`

@freezed
sealed class MetadataSourceError
    with _$MetadataSourceError
    implements FrbException {
  const MetadataSourceError._();

  const factory MetadataSourceError.aniList(String field0) =
      MetadataSourceError_AniList;
  const factory MetadataSourceError.myAnimeList(String field0) =
      MetadataSourceError_MyAnimeList;
  const factory MetadataSourceError.intParse(String field0) =
      MetadataSourceError_IntParse;
  const factory MetadataSourceError.precisionsParsing() =
      MetadataSourceError_PrecisionsParsing;
}
