// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.13.0-beta.5.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../../../frb_generated.dart';
import '../models.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `get_serie_status`
// These types are ignored because they are neither used by any `pub` functions nor (for structs and enums) marked `#[frb(unignore)]`: `MyAnimeListMetadata`
// These functions are ignored (category: IgnoreBecauseNotAllowedOwner): `english`, `get_id`, `get_image`, `get_name`, `japanese`, `official`, `romaji`, `synonyms`, `to_date_object`, `to_serie_metadata`, `to_slim`
// These functions are ignored (category: IgnoreBecauseOwnerTyShouldIgnore): `get_metadata_for_serie`, `search_metadata`

Future<SerieMetaConfidence> matchConfidence({required double precision}) =>
    RustLib.instance.api.crateApiDataMetadataMyanimelistMatchConfidence(
      precision: precision,
    );
