// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../../../frb_generated.dart';
import '../../../lib.dart';
import '../../app/configuration/models.dart';
import '../../app/languages.dart';
import '../../app/sections.dart';
import '../../app/themes.dart';
import '../../server/models.dart';
import '../models.dart';
import 'error.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `clone`, `clone`, `fmt`
// These functions are ignored (category: IgnoreBecauseExplicitAttribute): `call_search_metadata`, `choose_name`, `english`, `japanese`, `official`, `romaji`, `synonyms`
// These functions have error during generation (see debug logs or enable `stop_on_error: true` for more details): `get_metadata_for_serie`, `search_metadata`

/// If `source` is passed, only this `source` will be called.
/// Otherwise, all providers will be tested until the `serie_metadata` variable is `Some`.
///
/// Use the title to get possible metadata for a serie query and return the best match and its id
Future<SerieMetadata?> searchMetadata({
  required String query,
  required AnimeBoxConfig config,
  MetadataSources? source,
  required double precision,
}) => RustLib.instance.api.crateApiDataMetadataUtilsSearchMetadata(
  query: query,
  config: config,
  source: source,
  precision: precision,
);

Future<SerieMetadata?> getMetadata({
  required String id,
  required MetadataSources metadataSource,
}) => RustLib.instance.api.crateApiDataMetadataUtilsGetMetadata(
  id: id,
  metadataSource: metadataSource,
);

abstract class SlimMetaGetter {
  Future<int> getId();

  Future<String?> getImage();

  Future<String?> getName();
}

abstract class ToDateObject {
  Future<DateObject> toDateObject();
}

abstract class ToSerieMetadata {
  Future<SerieMetadata> toSerieMetadata();
}

abstract class ToSlimMeta {
  Future<SlimSerieMetadata> toSlim();
}

class MetadataSourceConfig {
  bool enabled;
  MetadataSources source;

  MetadataSourceConfig({required this.enabled, required this.source});

  @override
  int get hashCode => enabled.hashCode ^ source.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is MetadataSourceConfig &&
          runtimeType == other.runtimeType &&
          enabled == other.enabled &&
          source == other.source;
}

enum MetadataSources {
  myAnimeList,
  aniList;

  static Future<MetadataSources> default_() =>
      RustLib.instance.api.crateApiDataMetadataUtilsMetadataSourcesDefault();
}
