// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../../frb_generated.dart';
import 'metadata/utils.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These types are ignored because they are neither used by any `pub` functions nor (for structs and enums) marked `#[frb(unignore)]`: `AnimeSource`, `ChapterRef`, `ChapterVideos`, `Language`, `Search`, `Serie`, `VideoRef`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `clone`

class DateObject {
  final int? year;
  final int? month;
  final int? day;

  const DateObject({this.year, this.month, this.day});

  @override
  int get hashCode => year.hashCode ^ month.hashCode ^ day.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is DateObject &&
          runtimeType == other.runtimeType &&
          year == other.year &&
          month == other.month &&
          day == other.day;
}

class SearchResult {
  final String? name;
  final String? url;
  final String? image;

  const SearchResult({this.name, this.url, this.image});

  @override
  int get hashCode => name.hashCode ^ url.hashCode ^ image.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is SearchResult &&
          runtimeType == other.runtimeType &&
          name == other.name &&
          url == other.url &&
          image == other.image;
}

enum SerieMetaConfidence {
  confident,
  unsure,
  unable;

  static Future<SerieMetaConfidence> default_() =>
      RustLib.instance.api.crateApiDataModelsSerieMetaConfidenceDefault();
}

class SerieMetadata {
  final MetadataSources source;
  final PlatformInt64 fetchDate;
  final int id;
  final String? name;
  final String? image;
  final String? description;
  final SerieStatus status;
  final double findingPrecision;
  final SerieMetaConfidence findingConfidence;
  final List<String>? studios;
  final List<String>? genres;
  final DateObject? startDate;
  final DateObject? endDate;
  final List<SlimSerieMetadata> otherMatches;

  const SerieMetadata({
    required this.source,
    required this.fetchDate,
    required this.id,
    this.name,
    this.image,
    this.description,
    required this.status,
    required this.findingPrecision,
    required this.findingConfidence,
    this.studios,
    this.genres,
    this.startDate,
    this.endDate,
    required this.otherMatches,
  });

  static Future<SerieMetadata> default_() =>
      RustLib.instance.api.crateApiDataModelsSerieMetadataDefault();

  @override
  int get hashCode =>
      source.hashCode ^
      fetchDate.hashCode ^
      id.hashCode ^
      name.hashCode ^
      image.hashCode ^
      description.hashCode ^
      status.hashCode ^
      findingPrecision.hashCode ^
      findingConfidence.hashCode ^
      studios.hashCode ^
      genres.hashCode ^
      startDate.hashCode ^
      endDate.hashCode ^
      otherMatches.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is SerieMetadata &&
          runtimeType == other.runtimeType &&
          source == other.source &&
          fetchDate == other.fetchDate &&
          id == other.id &&
          name == other.name &&
          image == other.image &&
          description == other.description &&
          status == other.status &&
          findingPrecision == other.findingPrecision &&
          findingConfidence == other.findingConfidence &&
          studios == other.studios &&
          genres == other.genres &&
          startDate == other.startDate &&
          endDate == other.endDate &&
          otherMatches == other.otherMatches;
}

enum SerieStatus {
  ongoing,
  finished,
  upcoming,
  unknown;

  static Future<SerieStatus> default_() =>
      RustLib.instance.api.crateApiDataModelsSerieStatusDefault();
}

class SlimSerieMetadata {
  final int id;
  final String? name;
  final String? image;

  const SlimSerieMetadata({required this.id, this.name, this.image});

  @override
  int get hashCode => id.hashCode ^ name.hashCode ^ image.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is SlimSerieMetadata &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          name == other.name &&
          image == other.image;
}
