// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.13.0-beta.5.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../../../frb_generated.dart';
import '../../server/models.dart';
import '../models.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';
import 'package:freezed_annotation/freezed_annotation.dart' hide protected;
import 'utils.dart';
part 'anime_sources.freezed.dart';

// These types are ignored because they are neither used by any `pub` functions nor (for structs and enums) marked `#[frb(unignore)]`: `ServerSourcesResponse`, `ServerSources`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `clone`, `clone`, `fmt`, `fmt`, `fmt`
// These functions are ignored (category: IgnoreBecauseExplicitAttribute): `fmt`, `origin_path`
// These functions have error during generation (see debug logs or enable `stop_on_error: true` for more details): `refresh_sources`

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<AnimeSourcesCacheManager>>
abstract class AnimeSourcesCacheManager
    implements
        RustOpaqueInterface,
        AnimeSources,
        CacheSource,
        Expirable,
        GetPath,
        ReadWrite {
  PlatformInt64 get lastUpdate;

  Map<String, List<AnimeSource>> get sources;

  set lastUpdate(PlatformInt64 lastUpdate);

  set sources(Map<String, List<AnimeSource>> sources);

  static Future<AnimeSourcesCacheManager> default_() => RustLib.instance.api
      .crateApiDataCachingAnimeSourcesAnimeSourcesCacheManagerDefault();

  @override
  Future<PlatformInt64> getExpirationDate();

  @override
  Future<Map<String, List<AnimeSource>>> getSources();

  static Future<AnimeSourcesCacheManager> init() => RustLib.instance.api
      .crateApiDataCachingAnimeSourcesAnimeSourcesCacheManagerInit();

  @override
  Future<bool> isExpired();

  static Future<String> readFromFile() => RustLib.instance.api
      .crateApiDataCachingAnimeSourcesAnimeSourcesCacheManagerReadFromFile();

  Stream<RefreshJob> refreshSources({
    required bool forceFetch,
    required bool noFetch,
    required bool onlyMissing,
    required List<ConfigServer> servers,
  });

  @override
  Future<void> update();

  @override
  Future<void> writeToFile();
}

abstract class AnimeSources {
  Future<Map<String, List<AnimeSource>>> getSources();
}

@freezed
sealed class CacheRefreshError with _$CacheRefreshError {
  const CacheRefreshError._();

  const factory CacheRefreshError.connectionOrDeserializationFailed(
    String field0,
  ) = CacheRefreshError_ConnectionOrDeserializationFailed;
  const factory CacheRefreshError.invalidData() = CacheRefreshError_InvalidData;
}

class RefreshJob {
  final List<String> runningOn;
  final Map<String, CacheRefreshError> errors;
  final int success;
  final int error;
  final int total;

  const RefreshJob({
    required this.runningOn,
    required this.errors,
    required this.success,
    required this.error,
    required this.total,
  });

  @override
  int get hashCode =>
      runningOn.hashCode ^
      errors.hashCode ^
      success.hashCode ^
      error.hashCode ^
      total.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is RefreshJob &&
          runtimeType == other.runtimeType &&
          runningOn == other.runningOn &&
          errors == other.errors &&
          success == other.success &&
          error == other.error &&
          total == other.total;
}
