// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../../../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';
import 'package:freezed_annotation/freezed_annotation.dart' hide protected;
part 'utils.freezed.dart';

// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `fmt`, `fmt`, `from`

abstract class CacheSource {
  Future<void> update();
}

abstract class Expirable {
  Future<PlatformInt64> getExpirationDate();

  Future<bool> isExpired();
}

abstract class GetPath {}

abstract class ReadWrite {
  Future<void> writeToFile();
}

@freezed
sealed class CacheError with _$CacheError implements FrbException {
  const CacheError._();

  const factory CacheError.inputOutput(String field0) = CacheError_InputOutput;
}
