// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../../../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';
import 'package:freezed_annotation/freezed_annotation.dart' hide protected;
part 'error.freezed.dart';

// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `fmt`, `fmt`, `from`, `from`, `from`, `from`, `from`

@freezed
sealed class VideoProviderError
    with _$VideoProviderError
    implements FrbException {
  const VideoProviderError._();

  const factory VideoProviderError.urlNoPathSegments() =
      VideoProviderError_UrlNoPathSegments;
  const factory VideoProviderError.multiple(String field0) =
      VideoProviderError_Multiple;
  const factory VideoProviderError.packedScriptNotFound() =
      VideoProviderError_PackedScriptNotFound;
  const factory VideoProviderError.hls2UrlNotFound() =
      VideoProviderError_HLS2UrlNotFound;
  const factory VideoProviderError.jsUnpack(String field0) =
      VideoProviderError_JsUnpack;
  const factory VideoProviderError.regex(String field0) =
      VideoProviderError_Regex;
  const factory VideoProviderError.pixeldrain(String field0) =
      VideoProviderError_Pixeldrain;
  const factory VideoProviderError.url(String field0) = VideoProviderError_Url;
  const factory VideoProviderError.request(String field0) =
      VideoProviderError_Request;
}
