// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.13.0-beta.5.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../../../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';
import 'utils.dart';

class MP4Upload {
  const MP4Upload();

  Future<Video> getDirectVideo({required String url}) => RustLib.instance.api
      .crateApiDataVideoProvidersMp4UploadMp4UploadGetDirectVideo(
        that: this,
        url: url,
      );

  @override
  int get hashCode => 0;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is MP4Upload && runtimeType == other.runtimeType;
}
