// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../../../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';
import 'utils.dart';

class StreamWish {
  const StreamWish();

  Future<String> getContent({required String url}) => RustLib.instance.api
      .crateApiDataVideoProvidersStreamwishStreamWishGetContent(
        that: this,
        url: url,
      );

  Future<Video> getDirectVideo({required String url}) => RustLib.instance.api
      .crateApiDataVideoProvidersStreamwishStreamWishGetDirectVideo(
        that: this,
        url: url,
      );

  @override
  int get hashCode => 0;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is StreamWish && runtimeType == other.runtimeType;
}
