// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../../../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These types are ignored because they are neither used by any `pub` functions nor (for structs and enums) marked `#[frb(unignore)]`: `VideoProvider`
// These functions are ignored (category: IgnoreBecauseExplicitAttribute): `dumb_call`, `dumb_fetcher`, `headermap_to_hashmap`
// These functions have error during generation (see debug logs or enable `stop_on_error: true` for more details): `get_content`, `get_content`, `get_content`, `get_content`, `get_direct_video`

class Video {
  final String? url;
  final Map<String, String> headers;

  const Video({this.url, required this.headers});

  @override
  int get hashCode => url.hashCode ^ headers.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is Video &&
          runtimeType == other.runtimeType &&
          url == other.url &&
          headers == other.headers;
}
