[package]
name = "rust_lib_animebox"
version = "0.1.0"
edition = "2024"

[lib]
crate-type = ["cdylib", "staticlib"]

[dependencies]
ammonia = "4.1.2"
anilist_moe = "0.3.3"
anyhow = { version = "1.0.102", features = ["backtrace"] }
async-trait = "0.1.89"
chrono = "0.4.44"
flutter_rust_bridge = "=2.12.0"
heck = "0.5.0"
html-escape = "0.2.13"
jikan_moe = "0.2.5"
log = "0.4.29"
log4rs = "1.4.0"
regex = "1.12.3"
serde = { version = "1.0.228", features = ["derive"] }
serde_json = "1.0.149"
strsim = "0.11.1"
url = "2.5.8"
js-unpack = { git = "https://codeberg.org/iWisp360/js-unpack" }
ron = "0.12.1"
gql_client = { version = "1.1.0", features = [
  "rustls-tls",
], default-features = false }
debounce = "0.2.2"
tokio-util = "0.7.18"
tokio = { version = "1.52.3", features = ["full"] }
thiserror = "2.0.18"
uuid = "1.23.1"
rquickjs = { version = "0.12.0", features = ["macro"] }
rand = "0.10.1"

[dependencies.reqwest]
version = "0.12.28"
default-features = false
features = ["rustls-tls-webpki-roots", "rustls-tls"]

[target.'cfg(target_os = "linux")'.dependencies]
headless_chrome = "1.0.21"

[lints.rust]
unexpected_cfgs = { level = "warn", check-cfg = ['cfg(frb_expand)'] }
