// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../../frb_generated.dart';
import 'models.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

String? validateUrl({required String url}) =>
    RustLib.instance.api.crateApiServerHandlerValidateUrl(url: url);

Future<ConfigServer> getServer({required String url}) =>
    RustLib.instance.api.crateApiServerHandlerGetServer(url: url);
