// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These types are ignored because they are neither used by any `pub` functions nor (for structs and enums) marked `#[frb(unignore)]`: `AnimeSourceInfo`, `ServerLanguage`, `Server`

class ConfigServer {
  bool enabled;
  final String? name;
  final String url;
  final String? logoUrl;

  ConfigServer({
    required this.enabled,
    this.name,
    required this.url,
    this.logoUrl,
  });

  @override
  int get hashCode =>
      enabled.hashCode ^ name.hashCode ^ url.hashCode ^ logoUrl.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ConfigServer &&
          runtimeType == other.runtimeType &&
          enabled == other.enabled &&
          name == other.name &&
          url == other.url &&
          logoUrl == other.logoUrl;
}
