// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `clone`, `fmt`, `fmt`, `from`, `from`, `from`, `source`

Future<void> initLogger({required CoreLoggerSettings settings}) =>
    RustLib.instance.api.crateApiAppLoggingInitLogger(settings: settings);

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<LoggerError>>
abstract class LoggerError implements RustOpaqueInterface {}

class CoreLoggerSettings {
  final String path;
  final LogLevel level;

  const CoreLoggerSettings({required this.path, required this.level});

  @override
  int get hashCode => path.hashCode ^ level.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is CoreLoggerSettings &&
          runtimeType == other.runtimeType &&
          path == other.path &&
          level == other.level;
}

enum LogLevel { info, debug }
