// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `clone`, `clone`

enum ThemeModes {
  system,
  dark,
  light;

  static Future<ThemeModes> default_() =>
      RustLib.instance.api.crateApiAppThemesThemeModesDefault();
}

enum Themes {
  dynamic_,
  catppuccinLatte,
  catppuccinFrappe,
  catppuccinMacchiato,
  catppuccinMocha,
  nord,
  tokyoNight,
  matrix,
  monochrome;

  static Future<Themes> default_() =>
      RustLib.instance.api.crateApiAppThemesThemesDefault();
}
