// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../../../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';
import 'package:freezed_annotation/freezed_annotation.dart' hide protected;
part 'controllers.freezed.dart';

// These functions are ignored because they are not marked as `pub`: `write_config_to_file`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `fmt`, `fmt`, `from`, `from`, `from`, `from`

@freezed
sealed class ConfigError with _$ConfigError implements FrbException {
  const ConfigError._();

  const factory ConfigError.inputOutput(String field0) =
      ConfigError_InputOutput;
  const factory ConfigError.infallible(String field0) = ConfigError_Infallible;
  const factory ConfigError.ronSpanned(String field0) = ConfigError_RonSpanned;
  const factory ConfigError.ron(String field0) = ConfigError_Ron;
  const factory ConfigError.nonInitializedConfig() =
      ConfigError_NonInitializedConfig;
}
