// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../../../frb_generated.dart';
import '../../data/metadata/utils.dart';
import '../../server/models.dart';
import '../languages.dart';
import '../sections.dart';
import '../themes.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `default_metadata_sources`

class AdvancedConfig {
  bool debugLogs;
  String userAgent;

  AdvancedConfig({required this.debugLogs, required this.userAgent});

  static Future<AdvancedConfig> default_() => RustLib.instance.api
      .crateApiAppConfigurationModelsAdvancedConfigDefault();

  @override
  int get hashCode => debugLogs.hashCode ^ userAgent.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is AdvancedConfig &&
          runtimeType == other.runtimeType &&
          debugLogs == other.debugLogs &&
          userAgent == other.userAgent;
}

class AnimeBoxConfig {
  bool dataPathUninitialized;
  AppearanceConfig appearance;
  MetadataConfig metadata;
  DownloadsConfig downloads;
  PlaybackConfig playback;
  LibraryConfig library_;
  ServersConfig servers;
  LocalStorageConfig localStorage;
  AdvancedConfig advanced;

  AnimeBoxConfig({
    required this.dataPathUninitialized,
    required this.appearance,
    required this.metadata,
    required this.downloads,
    required this.playback,
    required this.library_,
    required this.servers,
    required this.localStorage,
    required this.advanced,
  });

  static Future<AnimeBoxConfig> default_() => RustLib.instance.api
      .crateApiAppConfigurationModelsAnimeBoxConfigDefault();

  static Future<AnimeBoxConfig> initConfig({required String path}) => RustLib
      .instance
      .api
      .crateApiAppConfigurationModelsAnimeBoxConfigInitConfig(path: path);

  Future<void> update() => RustLib.instance.api
      .crateApiAppConfigurationModelsAnimeBoxConfigUpdate(that: this);

  @override
  int get hashCode =>
      dataPathUninitialized.hashCode ^
      appearance.hashCode ^
      metadata.hashCode ^
      downloads.hashCode ^
      playback.hashCode ^
      library_.hashCode ^
      servers.hashCode ^
      localStorage.hashCode ^
      advanced.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is AnimeBoxConfig &&
          runtimeType == other.runtimeType &&
          dataPathUninitialized == other.dataPathUninitialized &&
          appearance == other.appearance &&
          metadata == other.metadata &&
          downloads == other.downloads &&
          playback == other.playback &&
          library_ == other.library_ &&
          servers == other.servers &&
          localStorage == other.localStorage &&
          advanced == other.advanced;
}

class AppearanceConfig {
  AppLanguages lang;
  HomeTabs initScreen;
  ThemeModes mode;
  Themes theme;
  bool relativeDates;
  bool pitchBlack;

  AppearanceConfig({
    required this.lang,
    required this.initScreen,
    required this.mode,
    required this.theme,
    required this.relativeDates,
    required this.pitchBlack,
  });

  static Future<AppearanceConfig> default_() => RustLib.instance.api
      .crateApiAppConfigurationModelsAppearanceConfigDefault();

  @override
  int get hashCode =>
      lang.hashCode ^
      initScreen.hashCode ^
      mode.hashCode ^
      theme.hashCode ^
      relativeDates.hashCode ^
      pitchBlack.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is AppearanceConfig &&
          runtimeType == other.runtimeType &&
          lang == other.lang &&
          initScreen == other.initScreen &&
          mode == other.mode &&
          theme == other.theme &&
          relativeDates == other.relativeDates &&
          pitchBlack == other.pitchBlack;
}

class DownloadsConfig {
  bool unmeteredNetworksOnly;
  String downloadedChaptersFormat;
  int maxThreads;

  DownloadsConfig({
    required this.unmeteredNetworksOnly,
    required this.downloadedChaptersFormat,
    required this.maxThreads,
  });

  static Future<DownloadsConfig> default_() => RustLib.instance.api
      .crateApiAppConfigurationModelsDownloadsConfigDefault();

  @override
  int get hashCode =>
      unmeteredNetworksOnly.hashCode ^
      downloadedChaptersFormat.hashCode ^
      maxThreads.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is DownloadsConfig &&
          runtimeType == other.runtimeType &&
          unmeteredNetworksOnly == other.unmeteredNetworksOnly &&
          downloadedChaptersFormat == other.downloadedChaptersFormat &&
          maxThreads == other.maxThreads;
}

class LibraryConfig {
  List<String> customCategories;
  String defCategory;
  UpdateParams updateParams;

  LibraryConfig({
    required this.customCategories,
    required this.defCategory,
    required this.updateParams,
  });

  static Future<LibraryConfig> default_() =>
      RustLib.instance.api.crateApiAppConfigurationModelsLibraryConfigDefault();

  @override
  int get hashCode =>
      customCategories.hashCode ^ defCategory.hashCode ^ updateParams.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is LibraryConfig &&
          runtimeType == other.runtimeType &&
          customCategories == other.customCategories &&
          defCategory == other.defCategory &&
          updateParams == other.updateParams;
}

class LocalStorageConfig {
  String dataPath;
  bool deleteWatchedChapters;
  bool enableBackup;
  bool enableAutomaticBackups;
  int backupInterval;

  LocalStorageConfig({
    required this.dataPath,
    required this.deleteWatchedChapters,
    required this.enableBackup,
    required this.enableAutomaticBackups,
    required this.backupInterval,
  });

  static Future<LocalStorageConfig> default_() => RustLib.instance.api
      .crateApiAppConfigurationModelsLocalStorageConfigDefault();

  @override
  int get hashCode =>
      dataPath.hashCode ^
      deleteWatchedChapters.hashCode ^
      enableBackup.hashCode ^
      enableAutomaticBackups.hashCode ^
      backupInterval.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is LocalStorageConfig &&
          runtimeType == other.runtimeType &&
          dataPath == other.dataPath &&
          deleteWatchedChapters == other.deleteWatchedChapters &&
          enableBackup == other.enableBackup &&
          enableAutomaticBackups == other.enableAutomaticBackups &&
          backupInterval == other.backupInterval;
}

class MetadataConfig {
  final List<MetadataSourceConfig> preferredMetaSources;

  const MetadataConfig({required this.preferredMetaSources});

  static Future<MetadataConfig> default_() => RustLib.instance.api
      .crateApiAppConfigurationModelsMetadataConfigDefault();

  @override
  int get hashCode => preferredMetaSources.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is MetadataConfig &&
          runtimeType == other.runtimeType &&
          preferredMetaSources == other.preferredMetaSources;
}

class PlaybackConfig {
  const PlaybackConfig();

  static Future<PlaybackConfig> default_() => RustLib.instance.api
      .crateApiAppConfigurationModelsPlaybackConfigDefault();

  @override
  int get hashCode => 0;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is PlaybackConfig && runtimeType == other.runtimeType;
}

class ServersConfig {
  List<ConfigServer> servers;

  ServersConfig({required this.servers});

  static Future<ServersConfig> default_() =>
      RustLib.instance.api.crateApiAppConfigurationModelsServersConfigDefault();

  @override
  int get hashCode => servers.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ServersConfig &&
          runtimeType == other.runtimeType &&
          servers == other.servers;
}

class UpdateParams {
  bool autoUpdatesEnable;
  int autoUpdatesInterval;
  bool customInterval;
  bool autoUpdatesMobileData;
  bool checkMetadataToo;
  bool avoidWatchedSeries;
  bool avoidCompletedSeries;

  UpdateParams({
    required this.autoUpdatesEnable,
    required this.autoUpdatesInterval,
    required this.customInterval,
    required this.autoUpdatesMobileData,
    required this.checkMetadataToo,
    required this.avoidWatchedSeries,
    required this.avoidCompletedSeries,
  });

  static Future<UpdateParams> default_() =>
      RustLib.instance.api.crateApiAppConfigurationModelsUpdateParamsDefault();

  @override
  int get hashCode =>
      autoUpdatesEnable.hashCode ^
      autoUpdatesInterval.hashCode ^
      customInterval.hashCode ^
      autoUpdatesMobileData.hashCode ^
      checkMetadataToo.hashCode ^
      avoidWatchedSeries.hashCode ^
      avoidCompletedSeries.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is UpdateParams &&
          runtimeType == other.runtimeType &&
          autoUpdatesEnable == other.autoUpdatesEnable &&
          autoUpdatesInterval == other.autoUpdatesInterval &&
          customInterval == other.customInterval &&
          autoUpdatesMobileData == other.autoUpdatesMobileData &&
          checkMetadataToo == other.checkMetadataToo &&
          avoidWatchedSeries == other.avoidWatchedSeries &&
          avoidCompletedSeries == other.avoidCompletedSeries;
}
